graylog_server_version: "0.20.2"
graylog_server_prefix: "/usr/local"
graylog_server_dir: "#{graylog_server_prefix}/graylog2-server-#{graylog_server_version}"
graylog_server_pid_file: "/var/run/graylog-server.pid"
graylog_server_port: 12201
graylog_server_syslog_port: 12514

graylog_web_version: "0.20.2"
graylog_web_prefix: "/usr/local"
graylog_web_dir: "#{graylog_web_prefix}/graylog2-web-interface-#{graylog_web_version}"
graylog_web_pid_file: "/var/run/graylog-web.pid"
graylog_web_port: 9000

graylog_web_username: admin
graylog_web_password: admin1

graylog_mongo_database: graylog2
graylog_elasticsearch_index: "graylog2_#{Rubber.env}"

web_tools_proxies:
  graylog:
    role: graylog_web
    port: "#{graylog_web_port}"
    path: /
  graylog_server_api_browser:
    role: graylog_server
    port: 12900
    path: /api-browser/

role_dependencies:
  graylog_server: [graylog_mongodb, graylog_elasticsearch]
  graylog_mongodb: [mongodb]
  graylog_elasticsearch: [elasticsearch]

roles:
  graylog_server:
    packages: [openjdk-7-jdk, mongodb-10gen]
  graylog_web:
    packages: [openjdk-7-jdk]

# This was auto-generated by Rubber and is unique to your machine.  Feel free to regenerate if you'd like.
# You may want to move this to your rubber-secret.yml to keep it out of version control.
graylog_server_secret: b447bdab3186b2da0ec607e3b40c28a0258b92ec79195c5208c5b0814051f71e55c8fea5c26b169ec1cfc0b02bf2189a3978dcbe665009c3e2e871555ddc47d395659d4404927993b58b9a5add3bd2090c2e0a2e230c443ecdb15f3501ecd0e0

# This was auto-generated by Rubber and is unique to your machine.  Feel free to regenerate if you'd like.
# You may want to move this to your rubber-secret.yml to keep it out of version control.
graylog_web_secret: a0ef74292f26e646fd97318b83fa468928048a7886684c273bcffedf0a2b8919652a2e8cc614a0915470d4375ee90182afcec44e8aee29cbc2662441aac0118e5b475d83f6b58b7c2cef9d31b008285756f97a00bc4e7073527ad27229b87cbd
